version: '3'
services:
  integration:
    build:
      context: .
      args:
        NOCACHE: ${NOCACHE:-False}
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    stdin_open: true
    tty: true
